/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/obsidian/plugin.ts
var plugin_exports = {};
__export(plugin_exports, {
  default: () => YTranscriptPlugin
});
module.exports = __toCommonJS(plugin_exports);
var import_obsidian5 = require("obsidian");

// src/youtube/parse-captions.ts
var TEXT_TAG_PATTERN = /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
var P_TAG_PATTERN = /<p\s+t="(\d+)"\s+d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
function parseCaptionXml(xmlContent) {
  const lines = [];
  for (const match of xmlContent.matchAll(TEXT_TAG_PATTERN)) {
    const startSeconds = parseFloat(match[1]);
    const durationSeconds = parseFloat(match[2]);
    const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
    if (text) {
      lines.push({
        text,
        offset: Math.round(startSeconds * 1e3),
        duration: Math.round(durationSeconds * 1e3)
      });
    }
  }
  if (lines.length === 0) {
    for (const match of xmlContent.matchAll(P_TAG_PATTERN)) {
      const offset = parseInt(match[1], 10);
      const duration = parseInt(match[2], 10);
      const text = decodeHtmlEntities(match[3].replace(/<[^>]+>/g, ""));
      if (text) {
        lines.push({ text, offset, duration });
      }
    }
  }
  return lines;
}
function decodeHtmlEntities(text) {
  return text.replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'").replace(
    /&#(\d+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 10))
  ).replace(
    /&#x([a-fA-F0-9]+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 16))
  ).replace(/\n/g, " ").trim();
}

// src/youtube/types.ts
var YouTubeTranscriptError = class extends Error {
  constructor(err) {
    if (!(err instanceof Error)) {
      super("Unknown transcript error");
      return;
    }
    if (err.message.includes("ERR_INVALID_URL")) {
      super("Invalid YouTube URL");
    } else {
      super(err.message);
    }
  }
};

// src/youtube/fetch.ts
var INNERTUBE_API_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";
var INNERTUBE_PLAYER_URL = `https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_API_KEY}`;
var INNERTUBE_CONTEXT = {
  client: {
    clientName: "IOS",
    clientVersion: "20.10.38",
    hl: "en",
    gl: "US"
  }
};
var IOS_USER_AGENT = "com.google.ios.youtube/20.10.38 (iPhone16,2; U; CPU iOS 17_5_1 like Mac OS X)";
async function fetchTranscript(url, http, config) {
  var _a, _b;
  try {
    const videoId = extractVideoIdFromUrl(url);
    if (!videoId) {
      throw new YouTubeTranscriptError(
        new Error("Invalid YouTube URL - could not extract video ID")
      );
    }
    const playerData = await fetchPlayerData(videoId, http, config);
    const title = ((_a = playerData.videoDetails) == null ? void 0 : _a.title) || "Unknown";
    const captionsData = (_b = playerData.captions) == null ? void 0 : _b.playerCaptionsTracklistRenderer;
    if (!captionsData || !captionsData.captionTracks) {
      throw new YouTubeTranscriptError(
        new Error("No captions available for this video")
      );
    }
    const langCode = (config == null ? void 0 : config.lang) || "en";
    const captionTrack = findCaptionTrack(
      captionsData.captionTracks,
      langCode
    );
    if (!captionTrack) {
      const availableLangs = captionsData.captionTracks.map((t) => t.languageCode).join(", ");
      throw new YouTubeTranscriptError(
        new Error(
          `No transcript found for language '${langCode}'. Available: ${availableLangs}`
        )
      );
    }
    const lines = await fetchTranscriptFromUrl(captionTrack.baseUrl, http);
    return {
      title: decodeHtml(title),
      lines
    };
  } catch (err) {
    if (err instanceof YouTubeTranscriptError) {
      throw err;
    }
    throw new YouTubeTranscriptError(err);
  }
}
function extractVideoIdFromUrl(url) {
  const patterns = [
    /(?:(?:youtube|youtube-nocookie)\.com\/(?:watch\?v=|embed\/|shorts\/|v\/|live\/)|youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) {
      return match[1];
    }
  }
  return null;
}
async function fetchPlayerData(videoId, http, config) {
  const context = {
    ...INNERTUBE_CONTEXT,
    client: {
      ...INNERTUBE_CONTEXT.client,
      hl: (config == null ? void 0 : config.lang) || "en",
      gl: (config == null ? void 0 : config.country) || "US"
    }
  };
  const body = JSON.stringify({ context, videoId });
  const responseText = await http.request({
    url: INNERTUBE_PLAYER_URL,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "User-Agent": IOS_USER_AGENT
    },
    body
  });
  const data = JSON.parse(responseText);
  const playabilityStatus = data.playabilityStatus;
  if (playabilityStatus) {
    if (playabilityStatus.status === "ERROR") {
      throw new Error(playabilityStatus.reason || "Video unavailable");
    }
    if (playabilityStatus.status === "LOGIN_REQUIRED") {
      throw new Error("This video requires login to view");
    }
    if (playabilityStatus.status === "UNPLAYABLE") {
      throw new Error(playabilityStatus.reason || "Video is unplayable");
    }
  }
  return data;
}
function findCaptionTrack(captionTracks, langCode) {
  let track = captionTracks.find((t) => t.languageCode === langCode);
  if (track) return track;
  track = captionTracks.find(
    (t) => t.languageCode.startsWith(langCode + "-")
  );
  if (track) return track;
  track = captionTracks.find(
    (t) => langCode.startsWith(t.languageCode + "-")
  );
  if (track) return track;
  if (captionTracks.length > 0) {
    return captionTracks[0];
  }
  return null;
}
async function fetchTranscriptFromUrl(transcriptUrl, http) {
  const responseText = await http.request({
    url: transcriptUrl,
    method: "GET",
    headers: {
      "Accept-Language": "en-US,en;q=0.9"
    }
  });
  if (responseText.length === 0) {
    throw new Error("Received empty transcript response");
  }
  return parseCaptionXml(responseText);
}
function decodeHtml(text) {
  return text.replace(/&#39;/g, "'").replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(
    /&#(\d+);/g,
    (_, code) => String.fromCharCode(parseInt(code, 10))
  ).replace(/\\n/g, " ").replace(/\s+/g, " ").trim();
}

// src/youtube/url.ts
var YOUTUBE_DOMAINS = /* @__PURE__ */ new Set([
  "youtube.com",
  "www.youtube.com",
  "m.youtube.com",
  "mobile.youtube.com",
  "music.youtube.com",
  "youtube-nocookie.com",
  "www.youtube-nocookie.com",
  "youtu.be",
  "www.youtu.be"
]);
var VIDEO_ID_PATTERN = /^[a-zA-Z0-9_-]{11}$/;
function isValidYouTubeUrl(url) {
  var _a;
  if (!url || typeof url !== "string") return false;
  let parsed;
  try {
    parsed = new URL(url);
  } catch (e) {
    return false;
  }
  const hostname = parsed.hostname.toLowerCase();
  if (!YOUTUBE_DOMAINS.has(hostname)) return false;
  if (hostname.endsWith("youtu.be")) {
    const [, videoId] = parsed.pathname.split("/");
    return VIDEO_ID_PATTERN.test(videoId != null ? videoId : "");
  }
  if (parsed.pathname === "/watch") {
    return VIDEO_ID_PATTERN.test((_a = parsed.searchParams.get("v")) != null ? _a : "");
  }
  const pathMatch = parsed.pathname.match(
    /^\/(?:embed|shorts|v|live)\/([a-zA-Z0-9_-]{11})(?:\/|$)/
  );
  return pathMatch !== null;
}
function extractYouTubeUrlFromText(text) {
  if (!text || typeof text !== "string") return null;
  const urlRegex = /https?:\/\/[^\s<>"{}|\\^`[\]]+/gi;
  const matches = text.match(urlRegex);
  if (!matches) return null;
  for (const match of matches) {
    if (isValidYouTubeUrl(match)) return match;
  }
  return null;
}
function buildTimestampUrl(url, offsetMs) {
  if (!url || typeof url !== "string") return "";
  try {
    const parsed = new URL(url);
    const seconds = Math.max(0, Math.floor(offsetMs / 1e3));
    parsed.searchParams.set("t", seconds.toString());
    return parsed.toString();
  } catch (e) {
    return url;
  }
}

// src/obsidian/commands/insert-transcript.ts
var import_obsidian3 = require("obsidian");

// src/transcript/blocks.ts
function getTranscriptBlocks(lines, timestampMod) {
  const blocks = [];
  let quote = "";
  let quoteTimeOffset = 0;
  lines.forEach((line, i) => {
    if (i === 0) {
      quoteTimeOffset = line.offset;
      quote += line.text + " ";
      return;
    }
    if (i % timestampMod === 0) {
      blocks.push({ quote, quoteTimeOffset });
      quote = "";
      quoteTimeOffset = line.offset;
    }
    quote += line.text + " ";
  });
  if (quote !== "") {
    blocks.push({ quote, quoteTimeOffset });
  }
  return blocks;
}

// src/transcript/timestamp.ts
var formatTimestamp = (t) => {
  if (t < 0) return "00:00";
  const fnum = (n) => `${n | 0}`.padStart(2, "0");
  const s = 1e3;
  const m = 60 * s;
  const h = 60 * m;
  const hours = Math.floor(t / h);
  const minutes = Math.floor((t - hours * h) / m);
  const seconds = Math.floor((t - hours * h - minutes * m) / s);
  const time = hours ? [hours, minutes, seconds] : [minutes, seconds];
  return time.map(fnum).join(":");
};

// src/transcript/format.ts
function formatTranscript(transcript, url, options) {
  if (!(transcript == null ? void 0 : transcript.lines) || !Array.isArray(transcript.lines)) return "";
  if (transcript.lines.length === 0) return "";
  const normalized = normalizeOptions(options);
  switch (normalized.template) {
    case "minimal":
      return formatMinimal(transcript);
    case "rich":
      return formatRich(transcript, url, normalized);
    case "standard":
    default:
      return formatStandard(transcript, url, normalized);
  }
}
function normalizeOptions(options) {
  var _a;
  const timestampMod = options.timestampMod <= 0 ? 1 : Math.max(1, Math.floor(options.timestampMod)) || 5;
  return {
    timestampMod,
    template: (_a = options.template) != null ? _a : "standard"
  };
}
function formatMinimal(transcript) {
  return transcript.lines.map((line) => line.text.trim()).filter((text) => text.length > 0).join(" ");
}
function formatStandard(transcript, url, options) {
  const blocks = getTranscriptBlocks(transcript.lines, options.timestampMod);
  if (blocks.length === 0) return "";
  return blocks.map(({ quote, quoteTimeOffset }) => {
    const timestamp = formatTimestamp(quoteTimeOffset);
    const href = url ? buildTimestampUrl(url, quoteTimeOffset) : "#";
    return `[${timestamp}](${href}) ${quote.trim()}`;
  }).join("\n");
}
function formatRich(transcript, url, options) {
  var _a;
  const title = ((_a = transcript.title) == null ? void 0 : _a.trim()) || "YouTube Transcript";
  const today = (/* @__PURE__ */ new Date()).toISOString().split("T")[0];
  const sourceUrl = url || "Unknown";
  const header = [
    `## ${title}`,
    `**Source**: ${sourceUrl}`,
    `**Retrieved**: ${today}`,
    ""
  ].join("\n");
  return header + formatStandard(transcript, url, options);
}

// src/obsidian/url-text-utils.ts
var UrlPattern = /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/gi;
function _getLinkNearestCursor(textLine, cursorPosition, linksInLine) {
  if (cursorPosition > textLine.length)
    throw new Error("Cursor out of the line");
  if (!linksInLine || linksInLine.length < 1)
    throw new Error("No links found");
  for (let i = 0; i < linksInLine.length; i++) {
    const link = linksInLine[i];
    const index = linksInLine.length > i + 1 ? textLine.indexOf(linksInLine[i + 1]) : textLine.length;
    if (cursorPosition <= index) return link;
  }
  throw new Error("Unexpected");
}
function getUrlFromText(lineText, cursorPosition) {
  var _a;
  const url = _getLinkNearestCursor(
    lineText,
    cursorPosition,
    (_a = lineText.match(UrlPattern)) != null ? _a : []
  );
  return [lineText.indexOf(url), lineText.indexOf(url) + url.length];
}

// src/obsidian/editor-extensions.ts
function getSelectedText(editor) {
  if (!editor.somethingSelected()) {
    const [from, to] = getWordBoundaries(editor);
    editor.setSelection(from, to);
  }
  return editor.getSelection();
}
function getWordBoundaries(editor) {
  const cursor = editor.getCursor();
  const lineText = editor.getLine(cursor.line);
  const urlPosition = getUrlFromText(lineText, cursor.ch);
  return [
    { line: cursor.line, ch: urlPosition[0] },
    { line: cursor.line, ch: urlPosition[1] }
  ];
}

// src/obsidian/http.ts
var import_obsidian = require("obsidian");
var obsidianHttp = {
  async request(req) {
    const res = await (0, import_obsidian.requestUrl)({
      url: req.url,
      method: req.method,
      headers: req.headers,
      body: req.body
    });
    return res.text;
  }
};

// src/obsidian/modals/prompt-modal.ts
var import_obsidian2 = require("obsidian");
var PromptModal = class extends import_obsidian2.Modal {
  constructor(app, initialValue) {
    super(app);
    this.submitted = false;
    this.initialValue = initialValue;
    this.value = initialValue || "";
  }
  listenInput(evt) {
    if (evt.key === "Enter") {
      evt.preventDefault();
      this.enterCallback(evt);
    }
  }
  onOpen() {
    this.titleEl.setText("YouTube URL");
    this.createForm();
  }
  onClose() {
    this.contentEl.empty();
    if (!this.submitted) {
      this.reject();
    }
  }
  createForm() {
    const textInput = new import_obsidian2.TextComponent(this.contentEl);
    textInput.inputEl.style.width = "100%";
    textInput.onChange((value) => this.value = value);
    textInput.inputEl.addEventListener(
      "keydown",
      (evt) => this.enterCallback(evt)
    );
    if (this.initialValue) {
      textInput.setValue(this.initialValue);
      textInput.inputEl.select();
    }
    textInput.inputEl.focus();
    const buttonDiv = this.modalEl.createDiv();
    buttonDiv.addClass("modal-button-container");
    const submitButton = new import_obsidian2.ButtonComponent(buttonDiv);
    submitButton.buttonEl.addClass("mod-cta");
    submitButton.setButtonText("Submit").onClick((evt) => {
      this.resolveAndClose(evt);
    });
  }
  enterCallback(evt) {
    if (evt.key === "Enter") {
      this.resolveAndClose(evt);
    }
  }
  resolveAndClose(evt) {
    this.submitted = true;
    evt.preventDefault();
    this.resolve(this.value);
    this.close();
  }
  async openAndGetValue(resolve, reject) {
    this.resolve = resolve;
    this.reject = reject;
    this.open();
  }
};

// src/obsidian/commands/insert-transcript.ts
var InsertTranscriptCommand = class {
  constructor(context) {
    this.context = context;
  }
  async execute(editor) {
    await this.executeWithOptions(editor, {});
  }
  async executeWithOptions(editor, options) {
    var _a;
    try {
      const url = await this.getYouTubeUrlWithConfirmation(editor);
      if (!url) return;
      if (!isValidYouTubeUrl(url)) {
        new import_obsidian3.Notice("Not a valid YouTube URL.");
        return;
      }
      const transcript = await fetchTranscript(
        url,
        obsidianHttp,
        this.transcriptConfig()
      );
      if (!((_a = transcript == null ? void 0 : transcript.lines) == null ? void 0 : _a.length)) {
        new import_obsidian3.Notice("No transcript available for this video.");
        return;
      }
      const formatted = formatTranscript(
        transcript,
        url,
        this.mergeFormatOptions(options)
      );
      if (!formatted.trim()) return;
      editor.replaceRange(formatted, editor.getCursor());
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      new import_obsidian3.Notice(`Insert transcript failed: ${message}`);
    }
  }
  async getYouTubeUrlWithConfirmation(editor) {
    const detectedUrl = await this.detectYouTubeUrl(editor);
    try {
      const prompt = new PromptModal(
        this.context.app,
        detectedUrl || void 0
      );
      const userUrl = await new Promise((resolve, reject) => {
        prompt.openAndGetValue(resolve, reject);
      });
      return userUrl.trim() || null;
    } catch (e) {
      return null;
    }
  }
  async detectYouTubeUrl(editor) {
    const selectionUrl = this.getUrlFromSelection(editor);
    if (selectionUrl) return selectionUrl;
    return this.getUrlFromClipboard();
  }
  getUrlFromSelection(editor) {
    try {
      const selectedText = editor.somethingSelected() ? editor.getSelection() : getSelectedText(editor);
      return extractYouTubeUrlFromText(selectedText);
    } catch (e) {
      return null;
    }
  }
  async getUrlFromClipboard() {
    try {
      const clipboardText = await navigator.clipboard.readText();
      return extractYouTubeUrlFromText(clipboardText);
    } catch (e) {
      return null;
    }
  }
  transcriptConfig() {
    var _a, _b;
    return {
      lang: (_a = this.context.settings) == null ? void 0 : _a.lang,
      country: (_b = this.context.settings) == null ? void 0 : _b.country
    };
  }
  mergeFormatOptions(options) {
    var _a, _b, _c, _d;
    return {
      template: (_a = options.template) != null ? _a : "standard",
      timestampMod: (_d = (_c = options.timestampMod) != null ? _c : (_b = this.context.settings) == null ? void 0 : _b.timestampMod) != null ? _d : 5
    };
  }
};

// src/obsidian/views/transcript-view.ts
var import_obsidian4 = require("obsidian");

// src/obsidian/highlight.ts
function highlightText(el, searchValue) {
  var _a;
  if (!searchValue) return;
  const needle = searchValue.toLowerCase();
  const walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  let node = walker.nextNode();
  while (node) {
    textNodes.push(node);
    node = walker.nextNode();
  }
  for (const textNode of textNodes) {
    const text = (_a = textNode.nodeValue) != null ? _a : "";
    const lower = text.toLowerCase();
    let searchFrom = 0;
    let matchIdx = lower.indexOf(needle, searchFrom);
    if (matchIdx === -1) continue;
    const parent = textNode.parentNode;
    if (!parent) continue;
    const fragment = document.createDocumentFragment();
    while (matchIdx !== -1) {
      if (matchIdx > searchFrom) {
        fragment.appendChild(
          document.createTextNode(text.slice(searchFrom, matchIdx))
        );
      }
      const mark = document.createElement("span");
      mark.className = "yt-transcript__highlight";
      mark.textContent = text.slice(matchIdx, matchIdx + needle.length);
      fragment.appendChild(mark);
      searchFrom = matchIdx + needle.length;
      matchIdx = lower.indexOf(needle, searchFrom);
    }
    if (searchFrom < text.length) {
      fragment.appendChild(
        document.createTextNode(text.slice(searchFrom))
      );
    }
    parent.replaceChild(fragment, textNode);
  }
}

// src/obsidian/views/transcript-view.ts
var TRANSCRIPT_TYPE_VIEW = "transcript-view";
var TranscriptView = class extends import_obsidian4.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentSearch = "";
    this.plugin = plugin;
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.createEl("h4", { text: "Transcript" });
  }
  async setEphemeralState(state) {
    const { url, transcript } = state;
    if (!url || !transcript) return;
    const { timestampMod } = this.plugin.settings;
    this.videoTitle = transcript.title;
    this.currentUrl = url;
    this.currentData = transcript;
    this.currentTimestampMod = timestampMod;
    this.currentSearch = "";
    this.contentEl.empty();
    const headerEl = this.contentEl.createEl("div", {
      cls: "yt-transcript__header"
    });
    headerEl.createEl("div", {
      text: transcript.title,
      cls: "yt-transcript__video-title",
      attr: { title: transcript.title }
    });
    if (transcript.lines.length === 0) {
      this.contentEl.createEl("div", {
        text: "No transcript found for this video.",
        cls: "yt-transcript__empty"
      });
      return;
    }
    const actionsEl = headerEl.createEl("div", {
      cls: "yt-transcript__actions"
    });
    this.renderSearchInput(actionsEl, url, transcript, timestampMod);
    this.renderIntervalInput(actionsEl);
    this.renderCopyAllButton(actionsEl);
    this.matchCountEl = headerEl.createEl("div", {
      cls: "yt-transcript__match-count"
    });
    this.dataContainerEl = this.contentEl.createEl("div", {
      cls: "yt-transcript__blocks"
    });
    this.renderTranscriptionBlocks(url, transcript, timestampMod, "");
  }
  renderSearchInput(parentEl, url, data, timestampMod) {
    const wrapperEl = parentEl.createEl("div", {
      cls: "yt-transcript__search"
    });
    const iconEl = wrapperEl.createEl("span", {
      cls: "yt-transcript__search-icon"
    });
    (0, import_obsidian4.setIcon)(iconEl, "search");
    const searchInputEl = wrapperEl.createEl("input", {
      cls: "yt-transcript__search-input"
    });
    searchInputEl.type = "text";
    searchInputEl.placeholder = "Search transcript";
    searchInputEl.addEventListener("input", (e) => {
      const value = e.target.value;
      this.currentSearch = value;
      this.renderTranscriptionBlocks(url, data, timestampMod, value);
    });
  }
  renderIntervalInput(parentEl) {
    var _a;
    const wrapperEl = parentEl.createEl("label", {
      cls: "yt-transcript__interval",
      attr: { title: "Lines grouped per timestamp" }
    });
    wrapperEl.createEl("span", {
      text: "Every",
      cls: "yt-transcript__interval-label"
    });
    const input = wrapperEl.createEl("input", {
      cls: "yt-transcript__interval-input"
    });
    input.type = "number";
    input.min = "1";
    input.step = "1";
    input.value = String((_a = this.currentTimestampMod) != null ? _a : 5);
    input.addEventListener("change", async () => {
      var _a2;
      const parsed = Number.parseInt(input.value, 10);
      if (Number.isNaN(parsed) || parsed < 1) {
        input.value = String((_a2 = this.currentTimestampMod) != null ? _a2 : 5);
        return;
      }
      this.currentTimestampMod = parsed;
      this.plugin.settings.timestampMod = parsed;
      await this.plugin.saveSettings();
      if (this.currentUrl && this.currentData) {
        this.renderTranscriptionBlocks(
          this.currentUrl,
          this.currentData,
          parsed,
          this.currentSearch
        );
      }
    });
  }
  renderCopyAllButton(parentEl) {
    const btn = parentEl.createEl("button", {
      cls: "yt-transcript__copy-all clickable-icon",
      attr: { "aria-label": "Copy all", title: "Copy all" }
    });
    (0, import_obsidian4.setIcon)(btn, "copy");
    btn.addEventListener("click", () => this.copyAll());
  }
  updateMatchCount(searchValue, count) {
    if (!this.matchCountEl) return;
    if (searchValue === "") {
      this.matchCountEl.setText("");
      this.matchCountEl.hide();
      return;
    }
    this.matchCountEl.show();
    this.matchCountEl.setText(
      count === 0 ? "No matches" : count === 1 ? "1 match" : `${count} matches`
    );
  }
  copyAll() {
    if (!this.currentUrl || !this.currentData || this.currentTimestampMod === void 0)
      return;
    const blocks = getTranscriptBlocks(
      this.currentData.lines,
      this.currentTimestampMod
    ).filter(
      (block) => block.quote.toLowerCase().includes(this.currentSearch.toLowerCase())
    );
    if (blocks.length === 0) return;
    navigator.clipboard.writeText(
      this.formatContentToPaste(this.currentUrl, blocks)
    );
    new import_obsidian4.Notice(
      this.currentSearch ? `Copied ${blocks.length} matching blocks` : "Copied transcript"
    );
  }
  formatContentToPaste(url, blocks) {
    return blocks.map((block) => {
      const { quote, quoteTimeOffset } = block;
      const href = url + "&t=" + Math.floor(quoteTimeOffset / 1e3);
      return `[${formatTimestamp(quoteTimeOffset)}](${href}) ${quote}`;
    }).join("\n");
  }
  renderTranscriptionBlocks(url, data, timestampMod, searchValue) {
    const dataContainerEl = this.dataContainerEl;
    if (dataContainerEl === void 0) return;
    dataContainerEl.empty();
    const transcriptBlocks = getTranscriptBlocks(data.lines, timestampMod);
    const filteredBlocks = transcriptBlocks.filter(
      (block) => block.quote.toLowerCase().includes(searchValue.toLowerCase())
    );
    this.updateMatchCount(searchValue, filteredBlocks.length);
    if (searchValue !== "" && filteredBlocks.length === 0) {
      dataContainerEl.createEl("div", {
        text: "No matches.",
        cls: "yt-transcript__empty"
      });
      return;
    }
    filteredBlocks.forEach((block) => {
      const { quote, quoteTimeOffset } = block;
      const blockContainerEl = createEl("div", {
        cls: "yt-transcript__transcript-block"
      });
      blockContainerEl.draggable = true;
      const timestampHref = url + "&t=" + Math.floor(quoteTimeOffset / 1e3);
      const linkEl = createEl("a", {
        text: formatTimestamp(quoteTimeOffset),
        cls: "external-link",
        attr: {
          href: timestampHref
        }
      });
      const span = dataContainerEl.createEl("span", {
        text: quote,
        title: "Click to copy"
      });
      span.addEventListener("click", (event) => {
        var _a;
        const target = event.target;
        if (target !== null) {
          navigator.clipboard.writeText((_a = target.textContent) != null ? _a : "");
        }
      });
      if (searchValue !== "") highlightText(span, searchValue);
      blockContainerEl.appendChild(linkEl);
      blockContainerEl.appendChild(span);
      blockContainerEl.addEventListener(
        "dragstart",
        (event) => {
          var _a;
          (_a = event.dataTransfer) == null ? void 0 : _a.setData(
            "text/html",
            blockContainerEl.innerHTML
          );
        }
      );
      blockContainerEl.addEventListener(
        "contextmenu",
        (event) => {
          const menu = new import_obsidian4.Menu();
          menu.addItem(
            (item) => item.setTitle("Copy all").onClick(() => {
              navigator.clipboard.writeText(
                this.formatContentToPaste(url, filteredBlocks)
              );
            })
          );
          menu.showAtPosition({ x: event.clientX, y: event.clientY });
        }
      );
      dataContainerEl.appendChild(blockContainerEl);
    });
  }
  getViewType() {
    return TRANSCRIPT_TYPE_VIEW;
  }
  getDisplayText() {
    var _a;
    return `Video: ${(_a = this.videoTitle) != null ? _a : "No name"}`;
  }
  getIcon() {
    return "scroll";
  }
};

// src/obsidian/plugin.ts
var DEFAULT_SETTINGS = {
  timestampMod: 5,
  lang: "en",
  country: "EN",
  openLocation: "right-sidebar"
};
var YTranscriptPlugin = class extends import_obsidian5.Plugin {
  async onload() {
    await this.loadSettings();
    this.insertTranscriptCommand = new InsertTranscriptCommand(this);
    this.registerView(
      TRANSCRIPT_TYPE_VIEW,
      (leaf) => new TranscriptView(leaf, this)
    );
    this.addCommand({
      id: "transcript-from-text",
      name: "Get YouTube transcript from selected url",
      editorCallback: (editor) => {
        const url = getSelectedText(editor).trim();
        this.openView(url);
      }
    });
    this.addCommand({
      id: "transcript-from-prompt",
      name: "Get YouTube transcript from url prompt",
      callback: async () => {
        const prompt = new PromptModal(this.app);
        const url = await new Promise(
          (resolve) => prompt.openAndGetValue(resolve, () => {
          })
        );
        if (url) {
          this.openView(url);
        }
      }
    });
    this.addCommand({
      id: "insert-youtube-transcript",
      name: "Insert YouTube transcript",
      editorCallback: async (editor) => {
        await this.insertTranscriptCommand.execute(editor);
      }
    });
    this.addSettingTab(new YTranscriptSettingTab(this.app, this));
  }
  async getTranscript(url, config) {
    var _a, _b;
    return fetchTranscript(url, obsidianHttp, {
      lang: (_a = config == null ? void 0 : config.lang) != null ? _a : this.settings.lang,
      country: (_b = config == null ? void 0 : config.country) != null ? _b : this.settings.country
    });
  }
  async openView(url) {
    if (!url) {
      new import_obsidian5.Notice("No YouTube URL provided.");
      return;
    }
    if (!isValidYouTubeUrl(url)) {
      new import_obsidian5.Notice("Not a valid YouTube URL.");
      return;
    }
    const notice = new import_obsidian5.Notice("Fetching transcript\u2026", 0);
    try {
      const transcript = await this.getTranscript(url);
      const leaf = this.getOpenLeaf();
      await leaf.setViewState({ type: TRANSCRIPT_TYPE_VIEW });
      this.app.workspace.revealLeaf(leaf);
      leaf.setEphemeralState({ url, transcript });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Unknown error";
      new import_obsidian5.Notice(`Failed to fetch transcript: ${message}`);
    } finally {
      notice.hide();
    }
  }
  getOpenLeaf() {
    const { workspace } = this.app;
    switch (this.settings.openLocation) {
      case "left-sidebar":
        return workspace.getLeftLeaf(false);
      case "tab":
        return workspace.getLeaf("tab");
      case "split":
        return workspace.getLeaf("split", "vertical");
      case "right-sidebar":
      default:
        return workspace.getRightLeaf(false);
    }
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(TRANSCRIPT_TYPE_VIEW);
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var YTranscriptSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings for YTranscript" });
    new import_obsidian5.Setting(containerEl).setName("Timestamp interval").setDesc(
      "Indicates how often timestamp should occur in text (1 - every line, 10 - every 10 lines)"
    ).addText(
      (text) => text.setValue(this.plugin.settings.timestampMod.toFixed()).onChange(async (value) => {
        const v = Number.parseInt(value);
        this.plugin.settings.timestampMod = Number.isNaN(v) ? 5 : v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Language").setDesc("Preferred transcript language").addText(
      (text) => text.setValue(this.plugin.settings.lang).onChange(async (value) => {
        this.plugin.settings.lang = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Country").setDesc("Preferred transcript country code").addText(
      (text) => text.setValue(this.plugin.settings.country).onChange(async (value) => {
        this.plugin.settings.country = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Open transcript in").setDesc("Where to open the transcript view").addDropdown(
      (dropdown) => dropdown.addOptions({
        "right-sidebar": "Right sidebar",
        "left-sidebar": "Left sidebar",
        tab: "New tab",
        split: "Split (right)"
      }).setValue(this.plugin.settings.openLocation).onChange(async (value) => {
        this.plugin.settings.openLocation = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

/* nosourcemap */